version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
  api:
    depends_on:
      - postgres
    image: gradecalc
    ports:
      - "8080:8080"
