name: Build

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - run: mvn clean package
      - run: docker build -t gradecalc .
      - run: docker compose up -d
