name: Build

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - run: ./mvnw clean package
      - run: ./mvnw test
    
